[local]
localhost

[mongodb]
mongodb.rajeswari.shop

[catalogue]
catalogue.rajeswari.shop

[redis]
redis.rajeswari.shop

[user]
user.rajeswari.shop

[cart]
cart.rajeswari.shop

[mysql]
mysql.rajeswari.shop

[shipping]
shipping.rajeswari.shop

[rabbitmq]
rabbitmq.rajeswari.shop

[payment]
payment.rajeswari.shop

[frontend]
frontend.rajeswari.shop